# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ss-lbl-gen',
                'doc_host': 'https://azaidi06.github.io',
                'git_url': 'https://github.com/azaidi06/ss-lbl-gen',
                'lib_path': 'ss_lbl_gen'},
  'syms': {'ss_lbl_gen.core': {'ss_lbl_gen.core.foo': ('core.html#foo', 'ss_lbl_gen/core.py')}}}
